### ISSUE TITLE
I want to contribute 

### ISSUE THREAD

**Issue by douglasdcm** [KvyatkovskyAleksey/ScrapeWebdriver#5]
Hi, how are you? I was searching for projects related to webdrivers and crawlers and I found this one that seems to be interesting. I'd like to contribute. Do you have roadmap?

**Comment by KvyatkovskyAleksey** [comment]
Hi! Sorry for late response. Feel free if you want to add something. I have not any roadmap now. Which functionality you want to add?

**Comment by douglasdcm** [comment]
Thank you! I'll it to test one library I've been working for for a while. As soon as it is done I'll send PR to get your opinion about it.
